### ISSUE TITLE
Update locket to comply with FedRamp standards

### ISSUE THREAD

**Issue by Talador12** [cloudflare/lockbox#10]
Now that a lot of tools are migrating to FedRamp compliance, some projects that are currently using Locket may have to migrate to new tools. Locket is the preferred way of managing secrets but this is certainly an issue that needs to be addressed or brought up.

**Comment by terinjokes** [comment]
Lockbox is a simple tool using NaCL's box, which uses best in class encryption. There is purposefully no options for any other encryption algorithms. I have no interest in making it configurable.
